# Generated by Django 5.1.3 on 2024-12-02 16:56

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('short_description', models.CharField(max_length=300, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('meta_description', models.CharField(blank=True, help_text='A brief summary of the content for search engines', max_length=160, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated list of keywords or topics related to the content', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Health_safety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', tinymce.models.HTMLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MajorProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.CharField(blank=True, max_length=1000, null=True)),
                ('scope', models.CharField(blank=True, max_length=1000, null=True)),
                ('facede_materials', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('description', tinymce.models.HTMLField(null=True)),
                ('featured_image', models.ImageField(null=True, upload_to='project_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('featured_image', models.ImageField(null=True, upload_to='product_images/')),
                ('short_description', models.CharField(max_length=500, null=True)),
                ('description', tinymce.models.HTMLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('featured_image', models.ImageField(null=True, upload_to='project_images/')),
                ('short_description', models.CharField(max_length=500, null=True)),
                ('description', tinymce.models.HTMLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='skylineFacade.majorprojects')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='skylineFacade.services')),
            ],
        ),
    ]
